Fixed to support optional user attributes is not valorized on IdP and setting a default value for subject claim only if no value is configured in IdP configuration
wso2-extensions/identity-outbound-auth-foursquare pull request #2
Opened 2017-05-14 16:42 UTC by vives

… setting a default value for subject claim only if no value is configured in IdP configuration

2017-05-16 13:49 UTC, malakasilva requested changes
Check the added comments and did not see sufficient debug logs in the code.

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			String tokenEndPoint = getTokenEndpoint(authenticatorProperties);
According to this it always takes the value from constants. Taking value from properties always ignored. Get the value from properties first then set to defaults.

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			if (tokenEndPoint == null) {
Check the above comment. This will never be executed.

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			OAuthClientRequest accessRequest;
Combine this with line 180

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +				OAuthClientResponse oAuthResponse;
Combine this and following line

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +		JSONObject userData;
Combine with the following line

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +				throw new ApplicationAuthenticatorException("Exception while casting the HttpURLConnection");
Put a better error message. What are the situation this can occur? invalid parameter? So user should be able to figure out soon

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +	private JSONObject fetchUserInfo(String url, String accessToken) throws ApplicationAuthenticatorException {
Put a meaningful name. Maybe call user info endpoint?

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +				return claims;
Better to put a warning log.

2017-05-16 13:49 UTC, malakasilva commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			JSONObject userClaims = new JSONObject();
I don't think we need another object for this purpose. Why can't we directly update the claim map. Just putting to a json object and iterating that end of the block in unwanted.

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			String tokenEndPoint = getTokenEndpoint(authenticatorProperties);
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			if (tokenEndPoint == null) {
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			OAuthClientRequest accessRequest;
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +				OAuthClientResponse oAuthResponse;
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +	private JSONObject fetchUserInfo(String url, String accessToken) throws ApplicationAuthenticatorException {
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +				throw new ApplicationAuthenticatorException("Exception while casting the HttpURLConnection");
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +		JSONObject userData;
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:17 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +				return claims;
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-17 13:18 UTC, vives commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticator.java
> +			JSONObject userClaims = new JSONObject();
Fixed in https://github.com/wso2-extensions/identity-outbound-auth-foursquare/pull/2/commits/58520246ef2e797650ce96df5d6f5fbde73cfa2d

2017-05-18 11:28 UTC, Kanapriya approved these changes

2017-05-18 11:29 UTC, Kanapriya approved these changes

2017-05-18 11:29 UTC, Kanapriya approved these changes

2017-05-18 11:56 UTC, malakasilva approved these changes

2017-05-18 11:57 UTC, merged

2017-09-04 07:54 UTC, pamod commented on component/src/main/java/org/wso2/carbon/identity/authenticator/FoursquareAuthenticatorConstants.java
> +	//Foursquare authorize endpoint URL.
Good if we could use block comments for this. This will be just the convention